### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by clagio** [venushka/jmxeval#2]
Hi,

i'm trying to use the expr tag to return the memory usage in GB.. 
<query var="heapMemoryMax" objectName="java.lang:type=Memory" compositeAttribute="HeapMemoryUsage" attribute="max" /> 
<expr var="heapMemoryMaxGb" expression="${heapMemoryMax}/1048576" />
but I receive the following error:
HeapMemory UNKNOWN - null [java.lang.NumberFormatException]

Am I using the expr tag in the wrong way?

**Comment by venushka** [comment]
I've just successfully ran it with the following xml file.

```xml
<jmxeval:jmxeval xmlns:jmxeval="http://www.adahas.com/schema/jmxeval-1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <connection url="service:jmx:rmi:///jndi/rmi://localhost:8090/jmxrmi">
    <eval name="heapMemory">
      <query var="heapMemoryMax" objectName="java.lang:type=Memory" compositeAttribute="HeapMemoryUsage" attribute="max" />
      <expr var="heapMemoryMaxGb" expression="${heapMemoryMax}/1048576" />
      <check useVar="heapMemoryMaxGb" warning="800" critical="600" message="Used heap memory = ${heapMemoryMaxGb}" />
    </eval>
  </connection>
</jmxeval:jmxeval>
```

Can you share the full xml file? (any sensitive data removed ofcourse)

**Comment by clagio** [comment]
I have the same error with your xml..
I'm using the latest version I think: jmxeval-2.0.0-SNAPSHOT
This is the check_jmxeval script:

> BASE_DIR=`dirname $0`
> LIB_DIR="$BASE_DIR/lib"
> $JAVA_HOME/bin/java -classpath "$BASE_DIR/jmxeval-2.0.0-SNAPSHOT.jar:$LIB_DIR/args4j-2.33.jar:$LIB_DIR/commons-io-2.5.jar:$LIB_DIR/commons-lang3-3.5.jar" com.adahas.tools.jmxeval.App $@

**Comment by venushka** [comment]
There were quite a lot of changes in master, unfortunately it could be that it was broken at the time you built it. I've just created a release from master. Could you please try this with 2.0.0 release?

If it still fails, can you run it again with `--verbose` in the command line to get the full stack trace and paste it here?

**Comment by clagio** [comment]
Perfect it's working now! :)

**Comment by venushka** [comment]
That's great! 👍
