### ISSUE TITLE
log4j2 CVE update - question

### ISSUE THREAD

**Issue by BBQigniter** [venushka/jmxeval#21]
Hi,

sorry, to bother.

I just saw that in the `pom.xml` there was an update to log4j 2.16 - https://github.com/venushka/jmxeval/blob/d1b75f2749099b3c382315aa333ccac78c6deda0/pom.xml

is it please possible to update to 2.17 and supply a new release? or is there somewhere a howto about building this from source?

thanks in advance!

**Comment by venushka** [comment]
Thanks for raising this. This is fixed in 3.1.1
