### ISSUE TITLE
Connect to a local vm via process id

### ISSUE THREAD

**Issue by thiesm** [venushka/jmxeval#3]
I'm working with an application server in a production environment.
I don't like to open an other port and than ensure that nobody else can access to it.
It is strongly recommended to use SSL an client certificates, which means a lot of work and even more support.

It looks easier to me, to use the direct attach to the vm by the PID (there is a PID-file anyway) like jconsol seams to do.
I have to ensure the restricted access to the system user anyway.

**Comment by venushka** [comment]
Agreed, for monitoring local processes direct attach would be the safest. I will have a look at adding direct attach support to this.

**Comment by venushka** [comment]
Hi @thiesm, I had a look at this, and the only way to do this is using the Attach API https://docs.oracle.com/javase/8/docs/technotes/guides/attach/index.html which seems to be part of tools.jar. I'm not sure how tools.jar can be included in to the Maven build.

**Comment by peterberkman** [comment]
ah, this would be a good addition - would solve my clear-text password problems!  here is a good (somewhat long) discussion on using tools.jar in a POM:

     https://stackoverflow.com/questions/3080437/jdk-tools-jar-as-maven-dependency

**Comment by venushka** [comment]
Hi @thiesm, @peterberkman

Thank you for your suggestions on this, I've added local attach support in the latest release 3.1.0. It would be great if you could have a look and see if it works for you.

**Comment by peterberkman** [comment]
Great news Venushka!

I’ll update and test asap!

Thank you!

~ Peter Berkman
[m]: +1 909 268-0084 | http://www.linkedin.com/in/pberkman
