### ISSUE TITLE
return value type when you execute an operation

### ISSUE THREAD

**Issue by vmosescu** [venushka/jmxeval#4]
If the return value type of an operation is a CompositeData you can not extract specific item values from it. It would be nice if exec tag has some extra attributes for this (similar with query tag).

**Comment by vmosescu** [comment]
can done very easy in Exec: 

      // invoke the method
      final Object returnValue = context.getConnection().invoke(mbeanName, operationName, argValues, argTypes);

      Object attributeValue;
      if (StringUtils.isBlank(attribute.get())){
        attributeValue = returnValue;
      } else {
        attributeValue = ((CompositeData)returnValue).get(attribute.get());
      }

      // set query result as variable
      context.setVar(var.get(), attributeValue);

**Comment by venushka** [comment]
Added to 3.0.0
