### ISSUE TITLE
Error: Could not find or load main class com.adahas.tools.jmxeval.App

### ISSUE THREAD

**Issue by SBMiddleware** [venushka/jmxeval#6]
Hi,

I'm trying to get this to work under Redhat but I cannot get it to work.  I keep getting the message; Error: Could not find or load main class com.adahas.tools.jmxeval.App

The check_jmxeval refers to jmxeval/lib directory which doesn't exist in your download.  Am I missing something?

Thanks,

**Comment by venushka** [comment]
Hi 

Did you download https://github.com/venushka/jmxeval/releases/download/release_3.1.0/jmxeval-3.1.0-bin.tar.gz? I just double checked and seems to have content in lib directory.

**Comment by SBMiddleware** [comment]
Hi Venushka,

Thank you for the URL.  I as looking at this one - https://github.com/venushka/jmxeval

I will use the new and thank you for the prompt response.

Thanks,

**Comment by venushka** [comment]
You are welcome, feel free to contact me if you have suggestions or issues.

**Comment by SBMiddleware** [comment]
Hi Venushka,

Hope you are well.

I have the check working fine from the command line but when running from Nagios I receive the error - (No output on stdout) stderr: Error: Could not find or load main class com.adahas.tools.jmxeval.App

My command looks like this in Nagios;
$USER1$/check_jmxeval jmxeval/conf/check-thread-count.xml --set host=$ARG1$ --set port=$ARG2$ --set warning=$ARG3$ --set critical=$ARG4$

Like this on the command line;
./check_jmxeval jmxeval/conf/check-thread-count.xml --set host=servername--set port=1214 --set warning=200 --set critical=205 --validate –verbose

I must be missing something.  Any ideas?

Thanks,

**Comment by venushka** [comment]
Hi

Did you get this resolved?

If not can you try adding the following line to the ```check_jmxeval``` file after ```BASE_DIR="`dirname $0`"```?

```echo "$BASE_DIR/jmxeval/lib/*:$JAVA_HOME/lib/tools.jar"```

so the script is like:

```
#!/bin/sh

BASE_DIR="`dirname $0`"
echo "$BASE_DIR/jmxeval/lib/*:$JAVA_HOME/lib/tools.jar"
"$JAVA_HOME/bin/java" -classpath "$BASE_DIR/jmxeval/lib/*:$JAVA_HOME/lib/tools.jar" com.adahas.tools.jmxeval.App $@
```

This should hopefully print the complete classpath. If I assume you've unpacked the tar.gz in to ```/opt/jmxeval-3.1.0``` directory and if your ```check_jmxeval``` file is located ```/opt/jmxeval-3.1.0/check_jmxeval```, can you check if the output is of the ```echo``` we added to the script prints something that starts with:

```/opt/jmxeval-3.1.0/jmxeval/lib/*:```

Then could you confirm that the directory ```/opt/jmxeval-3.1.0/jmxeval/lib/``` contains the 6 jar files shipped in the lib directory of the plugin?

**Comment by SBMiddleware** [comment]
Hi Venushka,

Yes, it was all sorted thanks.  Its working very well!

**Comment by venushka** [comment]
Glad you got it working! Cheers!
